version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: pgvector_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: ChangeMe
      POSTGRES_DB: api
    ports:
      - "5432:5432"
    restart: always
